import { PermissionResolvable } from "discord.js"
import { ArArgsType } from "../models/gema-models"

export const ErrorCodes = {
    EMPTY_RESPONSE_ERROR: 'No especificaste una respuesta para el autoresponder',
    AUTORESPONDER_ALREADY_EXISTS: 'Ya existe un autoresponder con ese nombre, prueba a editarlo con </autoresponder edit:1060706665630023772>',
    AUTORESPONDER_DOESNT_EXIST: 'No existe un autoresponder con ese nombre, prueba a crear uno con </autoresponder add:1060706665630023772>',
    INVALID_MATCHMODE_ERROR: 'El matchmode no  es válido, elige una de las opciones',
    INVALID_USER_ERROR: 'El usuario requerido no es válido. Asegúrate de que sea una mención o un ID',
    INVALID_CHANNEL_ERROR: 'El canal para la función requirechannel/denychannel/sendto no es una mención o un ID válido',
    INVALID_ROLE_ERROR: 'El rol para la función require-denyrole/add-removerole no es una mención o un ID válido',
    INVALID_ROLEUSER_ERROR: 'El usuario para la función add/removerole no es una mención o un ID válido',
    INVALID_EMBED_DATA_ERROR: 'El color o la descripcion para el embed no es válido',
    INVALID_PERM_ERROR: 'El permiso para la función \`requireperm\` no es válido. Selecciona un rol en \`Ajustes del servidor > Roles\` para visualizar los permisos válidos',
    INVALID_FONT_ERROR: 'La fuente para la función \`font\` no es válida',
    INVALID_TIME_FORMAT: 'El tiempo para la función \`deletereply\` debe ser un número. Ejemplo: \`{deletereply:1}\`',
    INVALID_RANGE: 'El rango para la función range no es válido. Uso: \`{range<número>:<1er número>-<2do número>}\`. Ejemplos: \`{range:1-50}\`, \`{range2:1-1000}\`',
    INVALID_CHOICES: 'Las opciones o el índice para la función \`choose\` no son válidos. Uso: \`{choose<número>:<opcion1>|<opcion2>|<opcion3>}\`.',
    INVALID_CHOICEVALUES: 'Los valores o el índice para la función \`choicevalues\` no son válidos. Uso: \`{choicevalues<número>:<valor1>|<valor2>|<valor3>}\`',
    INVALID_CORRECTCHOICE: 'El valor para la función \`correctchoice\` no es válida. Asegúrate de que sea una de las opciones de la función \`choice\` o \`choicevalues\`',
    INVALID_NICK: 'Debes especificar un nick para la función \`setnick\`',
    INVALID_ARGS_ERROR: 'El número o el tipo para la función \`requirearg\` no son válidos. Uso: \`{requirearg:<número>|<user/channel/color/role/number>}\`. Ejemplos: \`{requirearg:1}\`, \`{requirearg:2|channel}\`',
    INVALID_WAITRESPONSE: 'Debes especificar el tiempo, la respuesta a esperar y el mensaje que quieres que la bot envíe cuando detecte la respuesta. Uso:\`{waitresponse:<tiempo>|<respuesta a esperar>|<respuesta de la bot>}\`',
    INVALID_BUTTON_ERROR: '`Los datos para la función \`button\` no  son válidos',
    INVALID_BUTTONDATA_ERROR: 'Los datos para la función \`button\` no  son válidos. Si especificaste "5" (link) como el tipo, asegúrate de haber asignado un link válido. Uso:\`{button:<tipo>|<etiqueta>|<link o respuesta>}\`. Los tipos aceptados son "1" (azul), "2" (gris), "3" (verde), "4" (rojo), "5" (link)',
    INVALID_COOLDOWN: 'Debes especificar el tiempo en segundos para la función \`cooldown\`',
    INVALID_MODIFYBALL: 'Los datos para la función \`modifyball\` son incorrectos. Asegúrate de poner un número mayor a 0 o un usuario válido. Usos: \`{modifyball:<numero>}\` \`{modifyball:<usuario>|<numero>}\`',
    REACTION_ERROR: 'El emoji para la función react/reactreply no es válido',
    DELETE_MESSAGE_ERROR: 'No puedo eliminar el mensaje o ya fue eliminado. Por favor revise los datos de su autoresponder',
    ROLE_POSITION_ERROR: 'No puedo añadir o remover el rol especificado porque es más alto que el mío',
    ROLE_POSITION_ERROR2: 'No puedo cambiar el nick al miembro especificado porque tiene roles superiores a los míos',
    MEMBER_ISADMINISTRATOR: 'No puedo añadir o remover roles a un administrador',
    MEMBER_ISADMINISTRATOR2: 'No puedo cambiar el nick a un administrador',
    ADD_REMOVE_ROLE_ERROR: 'No puedo añadir o remover el rol especificado. Por favor revise los datos de su autoresponder',
    SET_NICK_ERROR: 'No puedo colocar el nick al usuario. Por favor revise los datos de su autoresponder',
    MODIFYBAL_ERROR: `La cantidad de 🍞 que se intentan quitar al usuario es superior a la cantidad en su balance`,
    CANNOT_SENDMESSAGE: function (e: Error) { `Ha ocurrido un error inesperado. ${e.toString()}` },
    REQUIRED_ARGS_ERROR: function (trigger: string, args: ArArgsType[]) { return `Necesitas especificar argumentos para este autoresponder. ` + this.CORRECT_ARGS_USE(trigger, args) },
    CORRECT_ARGS_USE: function (trigger: string, args: ArArgsType[]) { return `Uso: \`${trigger} ${args.map(arg => `<${arg.type || 'texto'}>`).join(' ')}\`` },
    INVALID_TYPEOF_ARG: function (type: string) { return `Debes especificar un ${type} válido para este autoresponder.` },
    NOT_ENOUGH_PERMS: function (perms: string[]) { return `No tengo los permisos necesarios para ejecutar la acción especificada.\nPermisos faltantes: ${perms.map(p => `\`${p}\``).join(', ')}` }
}