const { PermissionFlagsBits } = require('discord.js')

const Permissions = {
    Perms: [
        'CREATE_INSTANT_INVITE', 'KICK_MEMBERS',
        'BAN_MEMBERS',           'ADMINISTRATOR',
        'MANAGE_CHANNELS',       'MANAGE_GUILD',
        'ADD_REACTIONS',         'VIEW_AUDIT_LOG',
        'PRIORITY_SPEAKER',      'STREAM',
        'VIEW_CHANNEL',          'SEND_MESSAGES',
        'SEND_TTS_MESSAGES',     'MANAGE_MESSAGES',
        'EMBED_LINKS',           'ATTACH_FILES',
        'READ_MESSAGE_HISTORY',  'MENTION_EVERYONE',
        'USE_EXTERNAL_EMOJIS',   'VIEW_GUILD_INSIGHTS',
        'CONNECT',               'SPEAK',
        'MUTE_MEMBERS',          'DEAFEN_MEMBERS',
        'MOVE_MEMBERS',          'USE_VAD',
        'CHANGE_NICKNAME',       'MANAGE_NICKNAMES',
        'MANAGE_ROLES',          'MANAGE_WEBHOOKS',
        'MANAGE_EMOJIS'
      ]
}

const Permissions2 = {
  administrador: { flag: PermissionFlagsBits.Administrator, perm: 'Administrador' },
  crearInvitacion: { flag: PermissionFlagsBits.CreateInstantInvite, perm: 'Crear invitación' }, 
  expulsarMiembros: { flag: PermissionFlagsBits.KickMembers, perm: 'Expulsar miembros' },
  banearMiembros: { flag: PermissionFlagsBits.BanMembers, perm: 'Banear miembros' },
  gestionarCanales: { flag: PermissionFlagsBits.ManageChannels, perm: 'Gestionar canales' },
  añadirReacciones: { flag: PermissionFlagsBits.AddReactions, perm: 'Añadir reacciones' },
  silenciarMiembros: { flag: PermissionFlagsBits.MuteMembers, perm: 'Silenciar miembros' },
  prioridadDePalabra: { flag: PermissionFlagsBits.PrioritySpeaker, perm: 'Prioridad de palabra' },
  moverMiembros: { flag: PermissionFlagsBits.MoveMembers, perm: 'Mover miembros' },
  verCanal: { flag: PermissionFlagsBits.ViewChannel, perm: 'Ver canal' },
  cambiarApodo: { flag: PermissionFlagsBits.ChangeNickname, perm: 'Cambiar apodo' },
  enviarTTS: { flag: PermissionFlagsBits.SendTTSMessages, perm: 'Enviar mensajes de texto a voz' },
  gestionarRoles: { flag: PermissionFlagsBits.ManageRoles, perm: 'Gestionar roles' },
  insertarEnlaces: { flag: PermissionFlagsBits.EmbedLinks, perm: 'Insertar enlaces' },
  gestionarEmojisyStickers: { flag: PermissionFlagsBits.ManageEmojisAndStickers, perm: 'Gestionar emojis y stickers' },
  leerHistorial: { flag: PermissionFlagsBits.ReadMessageHistory, perm: 'Leer el historial de mensajes' },
  gestionarServidor: { flag: PermissionFlagsBits.ManageGuild, perm: 'Gestionar servidor' },
  usarEmojisExternos: { flag: PermissionFlagsBits.UseExternalEmojis, perm: 'Usar emojis externos' },
  verRegistroAuditoria: { flag: PermissionFlagsBits.ViewAuditLog, perm: 'Ver registro de auditoría' },
  usarStickersExternos: { flag: PermissionFlagsBits.UseExternalStickers, perm: 'Usar stickers externos' },
  video: { flag: PermissionFlagsBits.Stream, perm: 'Vídeo' },
  conectar: { flag: PermissionFlagsBits.Connect, perm: 'Conectar' },
  enviarMensajes: { flag: PermissionFlagsBits.SendMessages, perm: 'Enviar mensajes' },
  enviarMensajesHilos: { flag: PermissionFlagsBits.SendMessagesInThreads, perm: 'Enviar mensajes en hilos y publicaciones' },
  adjuntarArchivos: { flag: PermissionFlagsBits.AttachFiles, perm: 'Adjuntar archivos' },
  mencionarEveryone: { flag: PermissionFlagsBits.MentionEveryone, perm: 'Mencionar @everyone y @here' },
  verInformacionServidor: { flag: PermissionFlagsBits.ViewGuildInsights, perm: 'Ver información del servidor' },
  hablar: { flag: PermissionFlagsBits.Speak, perm: 'Hablar' },
  ensordecerMiembros: { flag: PermissionFlagsBits.DeafenMembers, perm: 'Ensordecer miembros' },
  usarComandos: { flag: PermissionFlagsBits.UseApplicationCommands, perm: 'Usar comandos de aplicaciones' },
  gestionarApodos: { flag: PermissionFlagsBits.ManageNicknames, perm: 'Gestionar apodos' },
  gestionarWebhooks: { flag: PermissionFlagsBits.ManageWebhooks, perm: 'Gestionar webhooks' },
  gestionarHilos: { flag: PermissionFlagsBits.ManageThreads, perm: 'Gestionar hilos y publicaciones' },
  gestionarMensajes: { flag: PermissionFlagsBits.ManageMessages, perm: 'Gestionar mensajes' }
}

const Permissions3 = [
  { flag: PermissionFlagsBits.Administrator, perm: 'Administrador' },
  { flag: PermissionFlagsBits.CreateInstantInvite, perm: 'Crear invitación' }, 
  { flag: PermissionFlagsBits.KickMembers, perm: 'Expulsar miembros' },
  { flag: PermissionFlagsBits.BanMembers, perm: 'Banear miembros' },
  { flag: PermissionFlagsBits.ManageChannels, perm: 'Gestionar canales' },
  { flag: PermissionFlagsBits.AddReactions, perm: 'Añadir reacciones' },
  { flag: PermissionFlagsBits.MuteMembers, perm: 'Silenciar miembros' },
  { flag: PermissionFlagsBits.PrioritySpeaker, perm: 'Prioridad de palabra' },
  { flag: PermissionFlagsBits.MoveMembers, perm: 'Mover miembros' },
  { flag: PermissionFlagsBits.ViewChannel, perm: 'Ver canal' },
  { flag: PermissionFlagsBits.ChangeNickname, perm: 'Cambiar apodo' },
  { flag: PermissionFlagsBits.SendTTSMessages, perm: 'Enviar mensajes de texto a voz' },
  { flag: PermissionFlagsBits.ManageRoles, perm: 'Gestionar roles' },
  { flag: PermissionFlagsBits.EmbedLinks, perm: 'Insertar enlaces' },
  { flag: PermissionFlagsBits.ManageEmojisAndStickers, perm: 'Gestionar emojis y stickers' },
  { flag: PermissionFlagsBits.ReadMessageHistory, perm: 'Leer el historial de mensajes' },
  { flag: PermissionFlagsBits.ManageGuild, perm: 'Gestionar servidor' },
  { flag: PermissionFlagsBits.UseExternalEmojis, perm: 'Usar emojis externos' },
  { flag: PermissionFlagsBits.ViewAuditLog, perm: 'Ver registro de auditoría' },
  { flag: PermissionFlagsBits.UseExternalStickers, perm: 'Usar stickers externos' },
  { flag: PermissionFlagsBits.Stream, perm: 'Vídeo' },
  { flag: PermissionFlagsBits.Connect, perm: 'Conectar' },
  { flag: PermissionFlagsBits.SendMessages, perm: 'Enviar mensajes' },
  { flag: PermissionFlagsBits.SendMessagesInThreads, perm: 'Enviar mensajes en hilos y publicaciones' },
  { flag: PermissionFlagsBits.AttachFiles, perm: 'Adjuntar archivos' },
  { flag: PermissionFlagsBits.MentionEveryone, perm: 'Mencionar @everyone y @here' },
  { flag: PermissionFlagsBits.ViewGuildInsights, perm: 'Ver información del servidor' },
  { flag: PermissionFlagsBits.Speak, perm: 'Hablar' },
  { flag: PermissionFlagsBits.DeafenMembers, perm: 'Ensordecer miembros' },
  { flag: PermissionFlagsBits.UseApplicationCommands, perm: 'Usar comandos de aplicaciones' },
  { flag: PermissionFlagsBits.ManageNicknames, perm: 'Gestionar apodos' },
  { flag: PermissionFlagsBits.ManageWebhooks, perm: 'Gestionar webhooks' },
  { flag: PermissionFlagsBits.ManageThreads, perm: 'Gestionar hilos y publicaciones' },
  { flag: PermissionFlagsBits.ManageMessagesm, perm: 'Gestionar mensajes' }
]

module.exports = { Permissions, Permissions2, Permissions3 }
